export const INCREMENT_COUNTER = 'INCREMENT_COUNTER';
export const DECREMENT_COUNTER = 'DECREMENT_COUNTER';
export const SAVE_COUNTRY = 'SAVE_COUNTRY';

export const REGISTER_USER = 'REGISTER_USER';
export const SET_LOGIN_USER = 'SET_LOGIN_USER';
export const SET_LOGOUT = 'SET_LOGOUT';
